### ISSUE TITLE
Command option still expects old parameter

### ISSUE THREAD

**Issue by hpeter2** [DrFreas/VCH#9]
**Describe the bug**
The option commands still expect the old parameters (rc, rp, rs, rt, td). 
Usage of the new parameters (added with v0.5.1 - rqc, rqp, rqs, rqt, rqd) responds with "Error: Could not process parameter for .vch option!"

**To Reproduce**
The old command `.vch option rc off` works
Command `.vch option rqc off` doesn't

**Additional context**
The commands save with the given parameter name, while the Startup settings read expects the new, making the commands broken.

Greets
HP

**Comment by DrFreas** [comment]
Hi Hendrik,
thank you for your message. I guess an old version of the dll somehow got uploaded since the corresponding code is correct.
Anyway a new version 0.6.0 is under construction and almost finished which I plan to release this weekend where this should definetly work like documented.

Greetings,
Jan

**Comment by DrFreas** [comment]
Hello again,
I did have a look into it and indeed while the code which listens to the command was correct, but the interpreting was not. This is now fixed in v0.6.1.

Thank you for the report!
